/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// AlertValueWidgetDefinitionType : Type of the alert value widget.

/// Type of the alert value widget.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AlertValueWidgetDefinitionType {
    #[serde(rename = "alert_value")]
    ALERT_VALUE,

}

impl ToString for AlertValueWidgetDefinitionType {
    fn to_string(&self) -> String {
        match self {
            Self::ALERT_VALUE => String::from("alert_value"),
        }
    }
}




