/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// AlertValueWidgetDefinition : Alert values are query values showing the current value of the metric in any monitor defined on your system.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlertValueWidgetDefinition {
    /// ID of the alert to use in the widget.
    #[serde(rename = "alert_id")]
    pub alert_id: String,
    /// Number of decimal to show. If not defined, will use the raw value.
    #[serde(rename = "precision", skip_serializing_if = "Option::is_none")]
    pub precision: Option<i64>,
    #[serde(rename = "text_align", skip_serializing_if = "Option::is_none")]
    pub text_align: Option<crate::models::WidgetTextAlign>,
    /// Title of the widget.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "title_align", skip_serializing_if = "Option::is_none")]
    pub title_align: Option<crate::models::WidgetTextAlign>,
    /// Size of value in the widget.
    #[serde(rename = "title_size", skip_serializing_if = "Option::is_none")]
    pub title_size: Option<String>,
    #[serde(rename = "type")]
    pub _type: crate::models::AlertValueWidgetDefinitionType,
    /// Unit to display with the value.
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
}

impl AlertValueWidgetDefinition {
    /// Alert values are query values showing the current value of the metric in any monitor defined on your system.
    pub fn new(alert_id: String, _type: crate::models::AlertValueWidgetDefinitionType) -> AlertValueWidgetDefinition {
        AlertValueWidgetDefinition {
            alert_id,
            precision: None,
            text_align: None,
            title: None,
            title_align: None,
            title_size: None,
            _type,
            unit: None,
        }
    }
}


