/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// AlertGraphWidgetDefinition : Alert graphs are timeseries graphs showing the current status of any monitor defined on your system.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlertGraphWidgetDefinition {
    /// ID of the alert to use in the widget.
    #[serde(rename = "alert_id")]
    pub alert_id: String,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<Box<crate::models::WidgetTime>>,
    /// The title of the widget.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "title_align", skip_serializing_if = "Option::is_none")]
    pub title_align: Option<crate::models::WidgetTextAlign>,
    /// Size of the title.
    #[serde(rename = "title_size", skip_serializing_if = "Option::is_none")]
    pub title_size: Option<String>,
    #[serde(rename = "type")]
    pub _type: crate::models::AlertGraphWidgetDefinitionType,
    #[serde(rename = "viz_type")]
    pub viz_type: crate::models::WidgetVizType,
}

impl AlertGraphWidgetDefinition {
    /// Alert graphs are timeseries graphs showing the current status of any monitor defined on your system.
    pub fn new(alert_id: String, _type: crate::models::AlertGraphWidgetDefinitionType, viz_type: crate::models::WidgetVizType) -> AlertGraphWidgetDefinition {
        AlertGraphWidgetDefinition {
            alert_id,
            time: None,
            title: None,
            title_align: None,
            title_size: None,
            _type,
            viz_type,
        }
    }
}


