/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ApiKey : Datadog API key.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKey {
    /// Date of creation of the API key.
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    /// Datadog user handle that created the API key.
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
    /// API key.
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Name of your API key.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl ApiKey {
    /// Datadog API key.
    pub fn new() -> ApiKey {
        ApiKey {
            created: None,
            created_by: None,
            key: None,
            name: None,
        }
    }
}


