/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ApiKeyListResponse : List of API and application keys available for a given organization.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyListResponse {
    /// Array of API keys.
    #[serde(rename = "api_keys", skip_serializing_if = "Option::is_none")]
    pub api_keys: Option<Vec<crate::models::ApiKey>>,
}

impl ApiKeyListResponse {
    /// List of API and application keys available for a given organization.
    pub fn new() -> ApiKeyListResponse {
        ApiKeyListResponse {
            api_keys: None,
        }
    }
}


