/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ApmStatsQueryDefinition : The APM stats query for table and distributions widgets.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApmStatsQueryDefinition {
    /// Column properties used by the front end for display.
    #[serde(rename = "columns", skip_serializing_if = "Option::is_none")]
    pub columns: Option<Vec<crate::models::ApmStatsQueryColumnType>>,
    /// Environment name.
    #[serde(rename = "env")]
    pub env: String,
    /// Operation name associated with service.
    #[serde(rename = "name")]
    pub name: String,
    /// The organization's host group name and value.
    #[serde(rename = "primary_tag")]
    pub primary_tag: String,
    /// Resource name.
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<String>,
    #[serde(rename = "row_type")]
    pub row_type: crate::models::ApmStatsQueryRowType,
    /// Service name.
    #[serde(rename = "service")]
    pub service: String,
}

impl ApmStatsQueryDefinition {
    /// The APM stats query for table and distributions widgets.
    pub fn new(env: String, name: String, primary_tag: String, row_type: crate::models::ApmStatsQueryRowType, service: String) -> ApmStatsQueryDefinition {
        ApmStatsQueryDefinition {
            columns: None,
            env,
            name,
            primary_tag,
            resource: None,
            row_type,
            service,
        }
    }
}


