/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// AwsLogsListServicesResponse : The list of current AWS services for which Datadog offers automatic log collection.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AwsLogsListServicesResponse {
    /// Key value in returned object.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Name of service available for configuration with Datadog logs.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl AwsLogsListServicesResponse {
    /// The list of current AWS services for which Datadog offers automatic log collection.
    pub fn new() -> AwsLogsListServicesResponse {
        AwsLogsListServicesResponse {
            id: None,
            label: None,
        }
    }
}


