/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// AwsLogsLambda : Description of the Lambdas.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AwsLogsLambda {
    /// Available ARN IDs.
    #[serde(rename = "arn", skip_serializing_if = "Option::is_none")]
    pub arn: Option<String>,
}

impl AwsLogsLambda {
    /// Description of the Lambdas.
    pub fn new() -> AwsLogsLambda {
        AwsLogsLambda {
            arn: None,
        }
    }
}


