/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// AwsLogsListResponse : A list of all Datadog-AWS logs integrations available in your Datadog organization.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AwsLogsListResponse {
    /// Your AWS Account ID without dashes.
    #[serde(rename = "account_id", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    /// List of ARNs configured in your Datadog account.
    #[serde(rename = "lambdas", skip_serializing_if = "Option::is_none")]
    pub lambdas: Option<Vec<crate::models::AwsLogsLambda>>,
    /// Array of services IDs.
    #[serde(rename = "services", skip_serializing_if = "Option::is_none")]
    pub services: Option<Vec<String>>,
}

impl AwsLogsListResponse {
    /// A list of all Datadog-AWS logs integrations available in your Datadog organization.
    pub fn new() -> AwsLogsListResponse {
        AwsLogsListResponse {
            account_id: None,
            lambdas: None,
            services: None,
        }
    }
}


