/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// AwsNamespace : The namespace associated with the tag filter entry.

/// The namespace associated with the tag filter entry.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AwsNamespace {
    #[serde(rename = "elb")]
    ELB,
    #[serde(rename = "application_elb")]
    APPLICATION_ELB,
    #[serde(rename = "sqs")]
    SQS,
    #[serde(rename = "rds")]
    RDS,
    #[serde(rename = "custom")]
    CUSTOM,
    #[serde(rename = "network_elb")]
    NETWORK_ELB,
    #[serde(rename = "lambda")]
    LAMBDA,

}

impl ToString for AwsNamespace {
    fn to_string(&self) -> String {
        match self {
            Self::ELB => String::from("elb"),
            Self::APPLICATION_ELB => String::from("application_elb"),
            Self::SQS => String::from("sqs"),
            Self::RDS => String::from("rds"),
            Self::CUSTOM => String::from("custom"),
            Self::NETWORK_ELB => String::from("network_elb"),
            Self::LAMBDA => String::from("lambda"),
        }
    }
}




