/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// AwsTagFilterCreateRequest : The objects used to set an AWS tag filter.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AwsTagFilterCreateRequest {
    /// Your AWS Account ID without dashes.
    #[serde(rename = "account_id", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<crate::models::AwsNamespace>,
    /// The tag filter string.
    #[serde(rename = "tag_filter_str", skip_serializing_if = "Option::is_none")]
    pub tag_filter_str: Option<String>,
}

impl AwsTagFilterCreateRequest {
    /// The objects used to set an AWS tag filter.
    pub fn new() -> AwsTagFilterCreateRequest {
        AwsTagFilterCreateRequest {
            account_id: None,
            namespace: None,
            tag_filter_str: None,
        }
    }
}


