/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// AwsTagFilterDeleteRequest : The objects used to delete an AWS tag filter entry.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AwsTagFilterDeleteRequest {
    /// The unique identifier of your AWS account.
    #[serde(rename = "account_id", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<crate::models::AwsNamespace>,
}

impl AwsTagFilterDeleteRequest {
    /// The objects used to delete an AWS tag filter entry.
    pub fn new() -> AwsTagFilterDeleteRequest {
        AwsTagFilterDeleteRequest {
            account_id: None,
            namespace: None,
        }
    }
}


