/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// CanceledDowntimesIds : Object containing array of IDs of canceled downtimes.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CanceledDowntimesIds {
    /// ID of downtimes that were canceled.
    #[serde(rename = "cancelled_ids", skip_serializing_if = "Option::is_none")]
    pub cancelled_ids: Option<Vec<i64>>,
}

impl CanceledDowntimesIds {
    /// Object containing array of IDs of canceled downtimes.
    pub fn new() -> CanceledDowntimesIds {
        CanceledDowntimesIds {
            cancelled_ids: None,
        }
    }
}


