/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// CheckCanDeleteSloResponse : A service level objective response containing the requested object.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckCanDeleteSloResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::CheckCanDeleteSloResponseData>>,
    /// A mapping of SLO id to it's current usages.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<::std::collections::HashMap<String, String>>,
}

impl CheckCanDeleteSloResponse {
    /// A service level objective response containing the requested object.
    pub fn new() -> CheckCanDeleteSloResponse {
        CheckCanDeleteSloResponse {
            data: None,
            errors: None,
        }
    }
}


