/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// CheckStatusWidgetDefinition : Check status shows the current status or number of results for any check performed.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckStatusWidgetDefinition {
    /// Name of the check to use in the widget.
    #[serde(rename = "check")]
    pub check: String,
    /// Group reporting a single check.
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    /// List of tag prefixes to group by in the case of a cluster check.
    #[serde(rename = "group_by", skip_serializing_if = "Option::is_none")]
    pub group_by: Option<Vec<String>>,
    #[serde(rename = "grouping")]
    pub grouping: crate::models::WidgetGrouping,
    /// List of tags used to filter the groups reporting a cluster check.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<Box<crate::models::WidgetTime>>,
    /// Title of the widget.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "title_align", skip_serializing_if = "Option::is_none")]
    pub title_align: Option<crate::models::WidgetTextAlign>,
    /// Size of the title.
    #[serde(rename = "title_size", skip_serializing_if = "Option::is_none")]
    pub title_size: Option<String>,
    #[serde(rename = "type")]
    pub _type: crate::models::CheckStatusWidgetDefinitionType,
}

impl CheckStatusWidgetDefinition {
    /// Check status shows the current status or number of results for any check performed.
    pub fn new(check: String, grouping: crate::models::WidgetGrouping, _type: crate::models::CheckStatusWidgetDefinitionType) -> CheckStatusWidgetDefinition {
        CheckStatusWidgetDefinition {
            check,
            group: None,
            group_by: None,
            grouping,
            tags: None,
            time: None,
            title: None,
            title_align: None,
            title_size: None,
            _type,
        }
    }
}


