/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// DashboardListDeleteResponse : Deleted dashboard details.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DashboardListDeleteResponse {
    /// ID of the deleted dashboard list.
    #[serde(rename = "deleted_dashboard_list_id", skip_serializing_if = "Option::is_none")]
    pub deleted_dashboard_list_id: Option<i64>,
}

impl DashboardListDeleteResponse {
    /// Deleted dashboard details.
    pub fn new() -> DashboardListDeleteResponse {
        DashboardListDeleteResponse {
            deleted_dashboard_list_id: None,
        }
    }
}


