/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// DashboardListListResponse : Information on your dashboard lists.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DashboardListListResponse {
    /// List of all your dashboard lists.
    #[serde(rename = "dashboard_lists", skip_serializing_if = "Option::is_none")]
    pub dashboard_lists: Option<Vec<crate::models::DashboardList>>,
}

impl DashboardListListResponse {
    /// Information on your dashboard lists.
    pub fn new() -> DashboardListListResponse {
        DashboardListListResponse {
            dashboard_lists: None,
        }
    }
}


