/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// DashboardTemplateVariablePreset : Template variables saved views.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DashboardTemplateVariablePreset {
    /// The name of the variable.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// List of variables.
    #[serde(rename = "template_variables", skip_serializing_if = "Option::is_none")]
    pub template_variables: Option<Vec<crate::models::DashboardTemplateVariablePresetValue>>,
}

impl DashboardTemplateVariablePreset {
    /// Template variables saved views.
    pub fn new() -> DashboardTemplateVariablePreset {
        DashboardTemplateVariablePreset {
            name: None,
            template_variables: None,
        }
    }
}


