/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// DashboardSummary : Dashboard summary response.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DashboardSummary {
    /// List of dashboard definitions.
    #[serde(rename = "dashboards", skip_serializing_if = "Option::is_none")]
    pub dashboards: Option<Vec<crate::models::DashboardSummaryDefinition>>,
}

impl DashboardSummary {
    /// Dashboard summary response.
    pub fn new() -> DashboardSummary {
        DashboardSummary {
            dashboards: None,
        }
    }
}


