/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// DashboardSummaryDefinition : Dashboard definition.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DashboardSummaryDefinition {
    /// Identifier of the dashboard author.
    #[serde(rename = "author_handle", skip_serializing_if = "Option::is_none")]
    pub author_handle: Option<String>,
    /// Creation date of the dashboard.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Description of the dashboard.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Dashboard identifier.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Whether this dashboard is read-only. If True, only the author and admins can make changes to it.
    #[serde(rename = "is_read_only", skip_serializing_if = "Option::is_none")]
    pub is_read_only: Option<bool>,
    #[serde(rename = "layout_type", skip_serializing_if = "Option::is_none")]
    pub layout_type: Option<crate::models::DashboardLayoutType>,
    /// Modification date of the dashboard.
    #[serde(rename = "modified_at", skip_serializing_if = "Option::is_none")]
    pub modified_at: Option<String>,
    /// Title of the dashboard.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// URL of the dashboard.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl DashboardSummaryDefinition {
    /// Dashboard definition.
    pub fn new() -> DashboardSummaryDefinition {
        DashboardSummaryDefinition {
            author_handle: None,
            created_at: None,
            description: None,
            id: None,
            is_read_only: None,
            layout_type: None,
            modified_at: None,
            title: None,
            url: None,
        }
    }
}


