/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// DistributionWidgetDefinition : The Distribution visualization is another way of showing metrics aggregated across one or several tags, such as hosts. Unlike the heat map, a distribution graph’s x-axis is quantity rather than time.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DistributionWidgetDefinition {
    /// (Deprecated) The widget legend was replaced by a tooltip and sidebar.
    #[serde(rename = "legend_size", skip_serializing_if = "Option::is_none")]
    pub legend_size: Option<String>,
    /// List of markers.
    #[serde(rename = "markers", skip_serializing_if = "Option::is_none")]
    pub markers: Option<Vec<crate::models::WidgetMarker>>,
    /// Array of one request object to display in the widget.  See the dedicated [Request JSON schema documentation](https://docs.datadoghq.com/dashboards/graphing_json/request_json)  to learn how to build the `REQUEST_SCHEMA`.
    #[serde(rename = "requests")]
    pub requests: Vec<crate::models::DistributionWidgetRequest>,
    /// (Deprecated) The widget legend was replaced by a tooltip and sidebar.
    #[serde(rename = "show_legend", skip_serializing_if = "Option::is_none")]
    pub show_legend: Option<bool>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<Box<crate::models::WidgetTime>>,
    /// Title of the widget.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "title_align", skip_serializing_if = "Option::is_none")]
    pub title_align: Option<crate::models::WidgetTextAlign>,
    /// Size of the title.
    #[serde(rename = "title_size", skip_serializing_if = "Option::is_none")]
    pub title_size: Option<String>,
    #[serde(rename = "type")]
    pub _type: crate::models::DistributionWidgetDefinitionType,
    #[serde(rename = "xaxis", skip_serializing_if = "Option::is_none")]
    pub xaxis: Option<Box<crate::models::DistributionWidgetXAxis>>,
    #[serde(rename = "yaxis", skip_serializing_if = "Option::is_none")]
    pub yaxis: Option<Box<crate::models::DistributionWidgetYAxis>>,
}

impl DistributionWidgetDefinition {
    /// The Distribution visualization is another way of showing metrics aggregated across one or several tags, such as hosts. Unlike the heat map, a distribution graph’s x-axis is quantity rather than time.
    pub fn new(requests: Vec<crate::models::DistributionWidgetRequest>, _type: crate::models::DistributionWidgetDefinitionType) -> DistributionWidgetDefinition {
        DistributionWidgetDefinition {
            legend_size: None,
            markers: None,
            requests,
            show_legend: None,
            time: None,
            title: None,
            title_align: None,
            title_size: None,
            _type,
            xaxis: None,
            yaxis: None,
        }
    }
}


