/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// EventListResponse : An event list response.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventListResponse {
    /// An array of events.
    #[serde(rename = "events", skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<crate::models::Event>>,
    /// A status.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl EventListResponse {
    /// An event list response.
    pub fn new() -> EventListResponse {
        EventListResponse {
            events: None,
            status: None,
        }
    }
}


