/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// EventStreamWidgetDefinition : The event stream is a widget version of the stream of events on the Event Stream view. Only available on FREE layout dashboards.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventStreamWidgetDefinition {
    #[serde(rename = "event_size", skip_serializing_if = "Option::is_none")]
    pub event_size: Option<crate::models::WidgetEventSize>,
    /// Query to filter the event stream with.
    #[serde(rename = "query")]
    pub query: String,
    /// The execution method for multi-value filters. Can be either and or or.
    #[serde(rename = "tags_execution", skip_serializing_if = "Option::is_none")]
    pub tags_execution: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<Box<crate::models::WidgetTime>>,
    /// Title of the widget.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "title_align", skip_serializing_if = "Option::is_none")]
    pub title_align: Option<crate::models::WidgetTextAlign>,
    /// Size of the title.
    #[serde(rename = "title_size", skip_serializing_if = "Option::is_none")]
    pub title_size: Option<String>,
    #[serde(rename = "type")]
    pub _type: crate::models::EventStreamWidgetDefinitionType,
}

impl EventStreamWidgetDefinition {
    /// The event stream is a widget version of the stream of events on the Event Stream view. Only available on FREE layout dashboards.
    pub fn new(query: String, _type: crate::models::EventStreamWidgetDefinitionType) -> EventStreamWidgetDefinition {
        EventStreamWidgetDefinition {
            event_size: None,
            query,
            tags_execution: None,
            time: None,
            title: None,
            title_align: None,
            title_size: None,
            _type,
        }
    }
}


