/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// EventAlertType : If an alert event is enabled, set its type. For example, `error`, `warning`, `info`, `success`, `user_update`, `recommendation`, and `snapshot`.

/// If an alert event is enabled, set its type. For example, `error`, `warning`, `info`, `success`, `user_update`, `recommendation`, and `snapshot`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventAlertType {
    #[serde(rename = "error")]
    ERROR,
    #[serde(rename = "warning")]
    WARNING,
    #[serde(rename = "info")]
    INFO,
    #[serde(rename = "success")]
    SUCCESS,
    #[serde(rename = "user_update")]
    USER_UPDATE,
    #[serde(rename = "recommendation")]
    RECOMMENDATION,
    #[serde(rename = "snapshot")]
    SNAPSHOT,

}

impl ToString for EventAlertType {
    fn to_string(&self) -> String {
        match self {
            Self::ERROR => String::from("error"),
            Self::WARNING => String::from("warning"),
            Self::INFO => String::from("info"),
            Self::SUCCESS => String::from("success"),
            Self::USER_UPDATE => String::from("user_update"),
            Self::RECOMMENDATION => String::from("recommendation"),
            Self::SNAPSHOT => String::from("snapshot"),
        }
    }
}




