/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// FormulaAndFunctionMetricQueryDefinition : A formula and functions metrics query.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FormulaAndFunctionMetricQueryDefinition {
    #[serde(rename = "aggregator", skip_serializing_if = "Option::is_none")]
    pub aggregator: Option<crate::models::FormulaAndFunctionMetricAggregation>,
    #[serde(rename = "data_source")]
    pub data_source: crate::models::FormulaAndFunctionMetricDataSource,
    /// Name of the query for use in formulas.
    #[serde(rename = "name")]
    pub name: String,
    /// Metrics query definition.
    #[serde(rename = "query")]
    pub query: String,
}

impl FormulaAndFunctionMetricQueryDefinition {
    /// A formula and functions metrics query.
    pub fn new(data_source: crate::models::FormulaAndFunctionMetricDataSource, name: String, query: String) -> FormulaAndFunctionMetricQueryDefinition {
        FormulaAndFunctionMetricQueryDefinition {
            aggregator: None,
            data_source,
            name,
            query,
        }
    }
}


