/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// FormulaAndFunctionEventsDataSource : Data source for event platform-based queries.

/// Data source for event platform-based queries.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FormulaAndFunctionEventsDataSource {
    #[serde(rename = "logs")]
    LOGS,
    #[serde(rename = "spans")]
    SPANS,
    #[serde(rename = "network")]
    NETWORK,
    #[serde(rename = "rum")]
    RUM,
    #[serde(rename = "security_signals")]
    SECURITY_SIGNALS,
    #[serde(rename = "profiles")]
    PROFILES,

}

impl ToString for FormulaAndFunctionEventsDataSource {
    fn to_string(&self) -> String {
        match self {
            Self::LOGS => String::from("logs"),
            Self::SPANS => String::from("spans"),
            Self::NETWORK => String::from("network"),
            Self::RUM => String::from("rum"),
            Self::SECURITY_SIGNALS => String::from("security_signals"),
            Self::PROFILES => String::from("profiles"),
        }
    }
}




