/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// FreeTextWidgetDefinition : Free text is a widget that allows you to add headings to your screenboard. Commonly used to state the overall purpose of the dashboard. Only available on FREE layout dashboards.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FreeTextWidgetDefinition {
    /// Color of the text.
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    /// Size of the text.
    #[serde(rename = "font_size", skip_serializing_if = "Option::is_none")]
    pub font_size: Option<String>,
    /// Text to display.
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "text_align", skip_serializing_if = "Option::is_none")]
    pub text_align: Option<crate::models::WidgetTextAlign>,
    #[serde(rename = "type")]
    pub _type: crate::models::FreeTextWidgetDefinitionType,
}

impl FreeTextWidgetDefinition {
    /// Free text is a widget that allows you to add headings to your screenboard. Commonly used to state the overall purpose of the dashboard. Only available on FREE layout dashboards.
    pub fn new(text: String, _type: crate::models::FreeTextWidgetDefinitionType) -> FreeTextWidgetDefinition {
        FreeTextWidgetDefinition {
            color: None,
            font_size: None,
            text,
            text_align: None,
            _type,
        }
    }
}


