/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// HostMuteResponse : Response with the list of muted host for your organization.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostMuteResponse {
    /// Action applied to the hosts.
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    /// POSIX timestamp in seconds when the host is unmuted.
    #[serde(rename = "end", skip_serializing_if = "Option::is_none")]
    pub end: Option<i64>,
    /// The host name.
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    /// Message associated with the mute.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl HostMuteResponse {
    /// Response with the list of muted host for your organization.
    pub fn new() -> HostMuteResponse {
        HostMuteResponse {
            action: None,
            end: None,
            hostname: None,
            message: None,
        }
    }
}


