/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// HostListResponse : Response with Host information from Datadog.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostListResponse {
    /// Array of hosts.
    #[serde(rename = "host_list", skip_serializing_if = "Option::is_none")]
    pub host_list: Option<Vec<crate::models::Host>>,
    /// Number of host matching the query.
    #[serde(rename = "total_matching", skip_serializing_if = "Option::is_none")]
    pub total_matching: Option<i64>,
    /// Number of host returned.
    #[serde(rename = "total_returned", skip_serializing_if = "Option::is_none")]
    pub total_returned: Option<i64>,
}

impl HostListResponse {
    /// Response with Host information from Datadog.
    pub fn new() -> HostListResponse {
        HostListResponse {
            host_list: None,
            total_matching: None,
            total_returned: None,
        }
    }
}


