/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// HostMuteSettings : Combination of settings to mute a host.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostMuteSettings {
    /// POSIX timestamp in seconds when the host is unmuted. If omitted, the host remains muted until explicitly unmuted.
    #[serde(rename = "end", skip_serializing_if = "Option::is_none")]
    pub end: Option<i64>,
    /// Message to associate with the muting of this host.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// If true and the host is already muted, replaces existing host mute settings.
    #[serde(rename = "override", skip_serializing_if = "Option::is_none")]
    pub _override: Option<bool>,
}

impl HostMuteSettings {
    /// Combination of settings to mute a host.
    pub fn new() -> HostMuteSettings {
        HostMuteSettings {
            end: None,
            message: None,
            _override: None,
        }
    }
}


