/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// HostMapWidgetDefinitionType : Type of the host map widget.

/// Type of the host map widget.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HostMapWidgetDefinitionType {
    #[serde(rename = "hostmap")]
    HOSTMAP,

}

impl ToString for HostMapWidgetDefinitionType {
    fn to_string(&self) -> String {
        match self {
            Self::HOSTMAP => String::from("hostmap"),
        }
    }
}




