/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// HostMeta : Metadata associated with your host.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostMeta {
    /// Array of Unix versions.
    #[serde(rename = "nixV", skip_serializing_if = "Option::is_none")]
    pub nix_v: Option<Vec<String>>,
}

impl HostMeta {
    /// Metadata associated with your host.
    pub fn new() -> HostMeta {
        HostMeta {
            nix_v: None,
        }
    }
}


