/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IFrameWidgetDefinition : The iframe widget allows you to embed a portion of any other web page on your dashboard. Only available on FREE layout dashboards.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IFrameWidgetDefinition {
    #[serde(rename = "type")]
    pub _type: crate::models::IFrameWidgetDefinitionType,
    /// URL of the iframe.
    #[serde(rename = "url")]
    pub url: String,
}

impl IFrameWidgetDefinition {
    /// The iframe widget allows you to embed a portion of any other web page on your dashboard. Only available on FREE layout dashboards.
    pub fn new(_type: crate::models::IFrameWidgetDefinitionType, url: String) -> IFrameWidgetDefinition {
        IFrameWidgetDefinition {
            _type,
            url,
        }
    }
}


