/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IFrameWidgetDefinitionType : Type of the iframe widget.

/// Type of the iframe widget.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IFrameWidgetDefinitionType {
    #[serde(rename = "iframe")]
    IFRAME,

}

impl ToString for IFrameWidgetDefinitionType {
    fn to_string(&self) -> String {
        match self {
            Self::IFRAME => String::from("iframe"),
        }
    }
}




