/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ImageWidgetDefinitionType : Type of the image widget.

/// Type of the image widget.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ImageWidgetDefinitionType {
    #[serde(rename = "image")]
    IMAGE,

}

impl ToString for ImageWidgetDefinitionType {
    fn to_string(&self) -> String {
        match self {
            Self::IMAGE => String::from("image"),
        }
    }
}




