/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// IntakePayloadAccepted : The payload accepted for intake.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntakePayloadAccepted {
    /// The status of the intake payload.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl IntakePayloadAccepted {
    /// The payload accepted for intake.
    pub fn new() -> IntakePayloadAccepted {
        IntakePayloadAccepted {
            status: None,
        }
    }
}


