/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// Log : Object describing a log after being processed and stored by Datadog.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Log {
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<Box<crate::models::LogContent>>,
    /// Unique ID of the Log.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl Log {
    /// Object describing a log after being processed and stored by Datadog.
    pub fn new() -> Log {
        Log {
            content: None,
            id: None,
        }
    }
}


