/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// LogQueryDefinitionGroupBySort : Define a sorting method.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogQueryDefinitionGroupBySort {
    /// The aggregation method.
    #[serde(rename = "aggregation")]
    pub aggregation: String,
    /// Facet name.
    #[serde(rename = "facet", skip_serializing_if = "Option::is_none")]
    pub facet: Option<String>,
    #[serde(rename = "order")]
    pub order: crate::models::WidgetSort,
}

impl LogQueryDefinitionGroupBySort {
    /// Define a sorting method.
    pub fn new(aggregation: String, order: crate::models::WidgetSort) -> LogQueryDefinitionGroupBySort {
        LogQueryDefinitionGroupBySort {
            aggregation,
            facet: None,
            order,
        }
    }
}


