/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// LogStreamWidgetDefinitionType : Type of the log stream widget.

/// Type of the log stream widget.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LogStreamWidgetDefinitionType {
    #[serde(rename = "log_stream")]
    LOG_STREAM,

}

impl ToString for LogStreamWidgetDefinitionType {
    fn to_string(&self) -> String {
        match self {
            Self::LOG_STREAM => String::from("log_stream"),
        }
    }
}




