/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// LogsArithmeticProcessorType : Type of logs arithmetic processor.

/// Type of logs arithmetic processor.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LogsArithmeticProcessorType {
    #[serde(rename = "arithmetic-processor")]
    ARITHMETIC_PROCESSOR,

}

impl ToString for LogsArithmeticProcessorType {
    fn to_string(&self) -> String {
        match self {
            Self::ARITHMETIC_PROCESSOR => String::from("arithmetic-processor"),
        }
    }
}




