/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// LogsMessageRemapperType : Type of logs message remapper.

/// Type of logs message remapper.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LogsMessageRemapperType {
    #[serde(rename = "message-remapper")]
    MESSAGE_REMAPPER,

}

impl ToString for LogsMessageRemapperType {
    fn to_string(&self) -> String {
        match self {
            Self::MESSAGE_REMAPPER => String::from("message-remapper"),
        }
    }
}




