/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// LogsTraceRemapperType : Type of logs trace remapper.

/// Type of logs trace remapper.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LogsTraceRemapperType {
    #[serde(rename = "trace-id-remapper")]
    TRACE_ID_REMAPPER,

}

impl ToString for LogsTraceRemapperType {
    fn to_string(&self) -> String {
        match self {
            Self::TRACE_ID_REMAPPER => String::from("trace-id-remapper"),
        }
    }
}




