/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// LogsIndex : Object describing a Datadog Log index.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogsIndex {
    /// The number of log events you can send in this index per day before you are rate-limited.
    #[serde(rename = "daily_limit", skip_serializing_if = "Option::is_none")]
    pub daily_limit: Option<i64>,
    /// An array of exclusion objects. The logs are tested against the query of each filter, following the order of the array. Only the first matching active exclusion matters, others (if any) are ignored.
    #[serde(rename = "exclusion_filters", skip_serializing_if = "Option::is_none")]
    pub exclusion_filters: Option<Vec<crate::models::LogsExclusion>>,
    #[serde(rename = "filter")]
    pub filter: Box<crate::models::LogsFilter>,
    /// A boolean stating if the index is rate limited, meaning more logs than the daily limit have been sent. Rate limit is reset every-day at 2pm UTC.
    #[serde(rename = "is_rate_limited", skip_serializing_if = "Option::is_none")]
    pub is_rate_limited: Option<bool>,
    /// The name of the index.
    #[serde(rename = "name")]
    pub name: String,
    /// The number of days before logs are deleted from this index. Available values depend on retention plans specified in your organization's contract/subscriptions.
    #[serde(rename = "num_retention_days", skip_serializing_if = "Option::is_none")]
    pub num_retention_days: Option<i64>,
}

impl LogsIndex {
    /// Object describing a Datadog Log index.
    pub fn new(filter: crate::models::LogsFilter, name: String) -> LogsIndex {
        LogsIndex {
            daily_limit: None,
            exclusion_filters: None,
            filter: Box::new(filter),
            is_rate_limited: None,
            name,
            num_retention_days: None,
        }
    }
}


