/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// LogsListResponse : Response object with all logs matching the request and pagination information.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogsListResponse {
    /// Array of logs matching the request and the `nextLogId` if sent.
    #[serde(rename = "logs", skip_serializing_if = "Option::is_none")]
    pub logs: Option<Vec<crate::models::Log>>,
    /// Hash identifier of the next log to return in the list. This parameter is used for the pagination feature.
    #[serde(rename = "nextLogId", skip_serializing_if = "Option::is_none")]
    pub next_log_id: Option<String>,
    /// Status of the response.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl LogsListResponse {
    /// Response object with all logs matching the request and pagination information.
    pub fn new() -> LogsListResponse {
        LogsListResponse {
            logs: None,
            next_log_id: None,
            status: None,
        }
    }
}


