/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// LogsListRequestTime : Timeframe to retrieve the log from.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogsListRequestTime {
    /// Minimum timestamp for requested logs.
    #[serde(rename = "from")]
    pub from: String,
    /// Timezone can be specified both as an offset (e.g. \"UTC+03:00\") or a regional zone (e.g. \"Europe/Paris\").
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    /// Maximum timestamp for requested logs.
    #[serde(rename = "to")]
    pub to: String,
}

impl LogsListRequestTime {
    /// Timeframe to retrieve the log from.
    pub fn new(from: String, to: String) -> LogsListRequestTime {
        LogsListRequestTime {
            from,
            timezone: None,
            to,
        }
    }
}


