/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// LogsDateRemapperType : Type of logs date remapper.

/// Type of logs date remapper.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LogsDateRemapperType {
    #[serde(rename = "date-remapper")]
    DATE_REMAPPER,

}

impl ToString for LogsDateRemapperType {
    fn to_string(&self) -> String {
        match self {
            Self::DATE_REMAPPER => String::from("date-remapper"),
        }
    }
}




