/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// LogsQueryCompute : Define computation for a log query.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogsQueryCompute {
    /// The aggregation method.
    #[serde(rename = "aggregation")]
    pub aggregation: String,
    /// Facet name.
    #[serde(rename = "facet", skip_serializing_if = "Option::is_none")]
    pub facet: Option<String>,
    /// Define a time interval in seconds.
    #[serde(rename = "interval", skip_serializing_if = "Option::is_none")]
    pub interval: Option<i64>,
}

impl LogsQueryCompute {
    /// Define computation for a log query.
    pub fn new(aggregation: String) -> LogsQueryCompute {
        LogsQueryCompute {
            aggregation,
            facet: None,
            interval: None,
        }
    }
}


