/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricsListResponse : Object listing all metric names stored by Datadog since a given time.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetricsListResponse {
    /// Time when the metrics were active, seconds since the Unix epoch.
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,
    /// List of metric names.
    #[serde(rename = "metrics", skip_serializing_if = "Option::is_none")]
    pub metrics: Option<Vec<String>>,
}

impl MetricsListResponse {
    /// Object listing all metric names stored by Datadog since a given time.
    pub fn new() -> MetricsListResponse {
        MetricsListResponse {
            from: None,
            metrics: None,
        }
    }
}


