/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MonitorState : Wrapper object with the different monitor states.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonitorState {
    /// Dictionary where the keys are groups (comma separated lists of tags) and the values are the list of groups your monitor is broken down on.
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<::std::collections::HashMap<String, crate::models::MonitorStateGroup>>,
}

impl MonitorState {
    /// Wrapper object with the different monitor states.
    pub fn new() -> MonitorState {
        MonitorState {
            groups: None,
        }
    }
}


