/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MonitorThresholds : List of the different monitor threshold available.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonitorThresholds {
    /// The monitor `CRITICAL` threshold.
    #[serde(rename = "critical", skip_serializing_if = "Option::is_none")]
    pub critical: Option<f64>,
    /// The monitor `CRITICAL` recovery threshold.
    #[serde(rename = "critical_recovery", skip_serializing_if = "Option::is_none")]
    pub critical_recovery: Option<f64>,
    /// The monitor `OK` threshold.
    #[serde(rename = "ok", skip_serializing_if = "Option::is_none")]
    pub ok: Option<f64>,
    /// The monitor UNKNOWN threshold.
    #[serde(rename = "unknown", skip_serializing_if = "Option::is_none")]
    pub unknown: Option<f64>,
    /// The monitor `WARNING` threshold.
    #[serde(rename = "warning", skip_serializing_if = "Option::is_none")]
    pub warning: Option<f64>,
    /// The monitor `WARNING` recovery threshold.
    #[serde(rename = "warning_recovery", skip_serializing_if = "Option::is_none")]
    pub warning_recovery: Option<f64>,
}

impl MonitorThresholds {
    /// List of the different monitor threshold available.
    pub fn new() -> MonitorThresholds {
        MonitorThresholds {
            critical: None,
            critical_recovery: None,
            ok: None,
            unknown: None,
            warning: None,
            warning_recovery: None,
        }
    }
}


