/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MonitorOptionsAggregation : Type of aggregation performed in the monitor query.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonitorOptionsAggregation {
    /// Group to break down the monitor on.
    #[serde(rename = "group_by", skip_serializing_if = "Option::is_none")]
    pub group_by: Option<String>,
    /// Metric name used in the monitor.
    #[serde(rename = "metric", skip_serializing_if = "Option::is_none")]
    pub metric: Option<String>,
    /// Metric type used in the monitor.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl MonitorOptionsAggregation {
    /// Type of aggregation performed in the monitor query.
    pub fn new() -> MonitorOptionsAggregation {
        MonitorOptionsAggregation {
            group_by: None,
            metric: None,
            _type: None,
        }
    }
}


