/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MonitorType : The type of the monitor. For more information about `type`, see the [monitor options](https://docs.datadoghq.com/monitors/guide/monitor_api_options/) docs.

/// The type of the monitor. For more information about `type`, see the [monitor options](https://docs.datadoghq.com/monitors/guide/monitor_api_options/) docs.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MonitorType {
    #[serde(rename = "composite")]
    COMPOSITE,
    #[serde(rename = "event alert")]
    EVENT_ALERT,
    #[serde(rename = "log alert")]
    LOG_ALERT,
    #[serde(rename = "metric alert")]
    METRIC_ALERT,
    #[serde(rename = "process alert")]
    PROCESS_ALERT,
    #[serde(rename = "query alert")]
    QUERY_ALERT,
    #[serde(rename = "rum alert")]
    RUM_ALERT,
    #[serde(rename = "service check")]
    SERVICE_CHECK,
    #[serde(rename = "synthetics alert")]
    SYNTHETICS_ALERT,
    #[serde(rename = "trace-analytics alert")]
    TRACE_ANALYTICS_ALERT,
    #[serde(rename = "slo alert")]
    SLO_ALERT,
    #[serde(rename = "event-v2 alert")]
    EVENT_V2_ALERT,

}

impl ToString for MonitorType {
    fn to_string(&self) -> String {
        match self {
            Self::COMPOSITE => String::from("composite"),
            Self::EVENT_ALERT => String::from("event alert"),
            Self::LOG_ALERT => String::from("log alert"),
            Self::METRIC_ALERT => String::from("metric alert"),
            Self::PROCESS_ALERT => String::from("process alert"),
            Self::QUERY_ALERT => String::from("query alert"),
            Self::RUM_ALERT => String::from("rum alert"),
            Self::SERVICE_CHECK => String::from("service check"),
            Self::SYNTHETICS_ALERT => String::from("synthetics alert"),
            Self::TRACE_ANALYTICS_ALERT => String::from("trace-analytics alert"),
            Self::SLO_ALERT => String::from("slo alert"),
            Self::EVENT_V2_ALERT => String::from("event-v2 alert"),
        }
    }
}




