/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// MonitorSummaryWidgetDefinition : The monitor summary widget displays a summary view of all your Datadog monitors, or a subset based on a query. Only available on FREE layout dashboards.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonitorSummaryWidgetDefinition {
    #[serde(rename = "color_preference", skip_serializing_if = "Option::is_none")]
    pub color_preference: Option<crate::models::WidgetColorPreference>,
    /// The number of monitors to display.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    #[serde(rename = "display_format", skip_serializing_if = "Option::is_none")]
    pub display_format: Option<crate::models::WidgetMonitorSummaryDisplayFormat>,
    /// Whether to show counts of 0 or not.
    #[serde(rename = "hide_zero_counts", skip_serializing_if = "Option::is_none")]
    pub hide_zero_counts: Option<bool>,
    /// Query to filter the monitors with.
    #[serde(rename = "query")]
    pub query: String,
    /// Whether to show the time that has elapsed since the monitor/group triggered.
    #[serde(rename = "show_last_triggered", skip_serializing_if = "Option::is_none")]
    pub show_last_triggered: Option<bool>,
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<crate::models::WidgetMonitorSummarySort>,
    /// The start of the list. Typically 0.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i64>,
    #[serde(rename = "summary_type", skip_serializing_if = "Option::is_none")]
    pub summary_type: Option<crate::models::WidgetSummaryType>,
    /// Title of the widget.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "title_align", skip_serializing_if = "Option::is_none")]
    pub title_align: Option<crate::models::WidgetTextAlign>,
    /// Size of the title.
    #[serde(rename = "title_size", skip_serializing_if = "Option::is_none")]
    pub title_size: Option<String>,
    #[serde(rename = "type")]
    pub _type: crate::models::MonitorSummaryWidgetDefinitionType,
}

impl MonitorSummaryWidgetDefinition {
    /// The monitor summary widget displays a summary view of all your Datadog monitors, or a subset based on a query. Only available on FREE layout dashboards.
    pub fn new(query: String, _type: crate::models::MonitorSummaryWidgetDefinitionType) -> MonitorSummaryWidgetDefinition {
        MonitorSummaryWidgetDefinition {
            color_preference: None,
            count: None,
            display_format: None,
            hide_zero_counts: None,
            query,
            show_last_triggered: None,
            sort: None,
            start: None,
            summary_type: None,
            title: None,
            title_align: None,
            title_size: None,
            _type,
        }
    }
}


