/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// NoteWidgetDefinition : The notes and links widget is similar to free text widget, but allows for more formatting options.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NoteWidgetDefinition {
    /// Background color of the note.
    #[serde(rename = "background_color", skip_serializing_if = "Option::is_none")]
    pub background_color: Option<String>,
    /// Content of the note.
    #[serde(rename = "content")]
    pub content: String,
    /// Size of the text.
    #[serde(rename = "font_size", skip_serializing_if = "Option::is_none")]
    pub font_size: Option<String>,
    /// Whether to add padding or not.
    #[serde(rename = "has_padding", skip_serializing_if = "Option::is_none")]
    pub has_padding: Option<bool>,
    /// Whether to show a tick or not.
    #[serde(rename = "show_tick", skip_serializing_if = "Option::is_none")]
    pub show_tick: Option<bool>,
    #[serde(rename = "text_align", skip_serializing_if = "Option::is_none")]
    pub text_align: Option<crate::models::WidgetTextAlign>,
    #[serde(rename = "tick_edge", skip_serializing_if = "Option::is_none")]
    pub tick_edge: Option<crate::models::WidgetTickEdge>,
    /// Where to position the tick on an edge.
    #[serde(rename = "tick_pos", skip_serializing_if = "Option::is_none")]
    pub tick_pos: Option<String>,
    #[serde(rename = "type")]
    pub _type: crate::models::NoteWidgetDefinitionType,
    #[serde(rename = "vertical_align", skip_serializing_if = "Option::is_none")]
    pub vertical_align: Option<crate::models::WidgetVerticalAlign>,
}

impl NoteWidgetDefinition {
    /// The notes and links widget is similar to free text widget, but allows for more formatting options.
    pub fn new(content: String, _type: crate::models::NoteWidgetDefinitionType) -> NoteWidgetDefinition {
        NoteWidgetDefinition {
            background_color: None,
            content,
            font_size: None,
            has_padding: None,
            show_tick: None,
            text_align: None,
            tick_edge: None,
            tick_pos: None,
            _type,
            vertical_align: None,
        }
    }
}


