/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// OrganizationListResponse : Response with the list of organizations.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationListResponse {
    /// Array of organization objects.
    #[serde(rename = "orgs", skip_serializing_if = "Option::is_none")]
    pub orgs: Option<Vec<crate::models::Organization>>,
}

impl OrganizationListResponse {
    /// Response with the list of organizations.
    pub fn new() -> OrganizationListResponse {
        OrganizationListResponse {
            orgs: None,
        }
    }
}


