/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// OrganizationSettings : A JSON array of settings.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationSettings {
    /// Whether or not the organization users can share widgets outside of Datadog.
    #[serde(rename = "private_widget_share", skip_serializing_if = "Option::is_none")]
    pub private_widget_share: Option<bool>,
    #[serde(rename = "saml", skip_serializing_if = "Option::is_none")]
    pub saml: Option<Box<crate::models::OrganizationSettingsSaml>>,
    #[serde(rename = "saml_autocreate_access_role", skip_serializing_if = "Option::is_none")]
    pub saml_autocreate_access_role: Option<crate::models::AccessRole>,
    #[serde(rename = "saml_autocreate_users_domains", skip_serializing_if = "Option::is_none")]
    pub saml_autocreate_users_domains: Option<Box<crate::models::OrganizationSettingsSamlAutocreateUsersDomains>>,
    /// Whether or not SAML can be enabled for this organization.
    #[serde(rename = "saml_can_be_enabled", skip_serializing_if = "Option::is_none")]
    pub saml_can_be_enabled: Option<bool>,
    /// Identity provider endpoint for SAML authentication.
    #[serde(rename = "saml_idp_endpoint", skip_serializing_if = "Option::is_none")]
    pub saml_idp_endpoint: Option<String>,
    #[serde(rename = "saml_idp_initiated_login", skip_serializing_if = "Option::is_none")]
    pub saml_idp_initiated_login: Option<Box<crate::models::OrganizationSettingsSamlIdpInitiatedLogin>>,
    /// Whether or not a SAML identity provider metadata file was provided to the Datadog organization.
    #[serde(rename = "saml_idp_metadata_uploaded", skip_serializing_if = "Option::is_none")]
    pub saml_idp_metadata_uploaded: Option<bool>,
    /// URL for SAML logging.
    #[serde(rename = "saml_login_url", skip_serializing_if = "Option::is_none")]
    pub saml_login_url: Option<String>,
    #[serde(rename = "saml_strict_mode", skip_serializing_if = "Option::is_none")]
    pub saml_strict_mode: Option<Box<crate::models::OrganizationSettingsSamlStrictMode>>,
}

impl OrganizationSettings {
    /// A JSON array of settings.
    pub fn new() -> OrganizationSettings {
        OrganizationSettings {
            private_widget_share: None,
            saml: None,
            saml_autocreate_access_role: None,
            saml_autocreate_users_domains: None,
            saml_can_be_enabled: None,
            saml_idp_endpoint: None,
            saml_idp_initiated_login: None,
            saml_idp_metadata_uploaded: None,
            saml_login_url: None,
            saml_strict_mode: None,
        }
    }
}


