/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// OrganizationResponse : Response with an organization.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationResponse {
    #[serde(rename = "org", skip_serializing_if = "Option::is_none")]
    pub org: Option<Box<crate::models::Organization>>,
}

impl OrganizationResponse {
    /// Response with an organization.
    pub fn new() -> OrganizationResponse {
        OrganizationResponse {
            org: None,
        }
    }
}


