/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// OrganizationSettingsSaml : Set the boolean property enabled to enable or disable single sign on with SAML. See the SAML documentation for more information about all SAML settings.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationSettingsSaml {
    /// Whether or not SAML is enabled for this organization.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl OrganizationSettingsSaml {
    /// Set the boolean property enabled to enable or disable single sign on with SAML. See the SAML documentation for more information about all SAML settings.
    pub fn new() -> OrganizationSettingsSaml {
        OrganizationSettingsSaml {
            enabled: None,
        }
    }
}


