/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// OrganizationCreateResponse : Response object for an organization creation.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationCreateResponse {
    #[serde(rename = "api_key", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<Box<crate::models::ApiKey>>,
    #[serde(rename = "application_key", skip_serializing_if = "Option::is_none")]
    pub application_key: Option<Box<crate::models::ApplicationKey>>,
    #[serde(rename = "org", skip_serializing_if = "Option::is_none")]
    pub org: Option<Box<crate::models::Organization>>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<crate::models::User>>,
}

impl OrganizationCreateResponse {
    /// Response object for an organization creation.
    pub fn new() -> OrganizationCreateResponse {
        OrganizationCreateResponse {
            api_key: None,
            application_key: None,
            org: None,
            user: None,
        }
    }
}


