/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ProcessQueryDefinition : The process query to use in the widget.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProcessQueryDefinition {
    /// List of processes.
    #[serde(rename = "filter_by", skip_serializing_if = "Option::is_none")]
    pub filter_by: Option<Vec<String>>,
    /// Max number of items in the filter list.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// Your chosen metric.
    #[serde(rename = "metric")]
    pub metric: String,
    /// Your chosen search term.
    #[serde(rename = "search_by", skip_serializing_if = "Option::is_none")]
    pub search_by: Option<String>,
}

impl ProcessQueryDefinition {
    /// The process query to use in the widget.
    pub fn new(metric: String) -> ProcessQueryDefinition {
        ProcessQueryDefinition {
            filter_by: None,
            limit: None,
            metric,
            search_by: None,
        }
    }
}


