/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ScatterPlotWidgetDefinitionType : Type of the scatter plot widget.

/// Type of the scatter plot widget.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ScatterPlotWidgetDefinitionType {
    #[serde(rename = "scatterplot")]
    SCATTERPLOT,

}

impl ToString for ScatterPlotWidgetDefinitionType {
    fn to_string(&self) -> String {
        match self {
            Self::SCATTERPLOT => String::from("scatterplot"),
        }
    }
}




