/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// ServiceSummaryWidgetDefinition : The service summary displays the graphs of a chosen service in your screenboard. Only available on FREE layout dashboards.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceSummaryWidgetDefinition {
    #[serde(rename = "display_format", skip_serializing_if = "Option::is_none")]
    pub display_format: Option<crate::models::WidgetServiceSummaryDisplayFormat>,
    /// APM environment.
    #[serde(rename = "env")]
    pub env: String,
    /// APM service.
    #[serde(rename = "service")]
    pub service: String,
    /// Whether to show the latency breakdown or not.
    #[serde(rename = "show_breakdown", skip_serializing_if = "Option::is_none")]
    pub show_breakdown: Option<bool>,
    /// Whether to show the latency distribution or not.
    #[serde(rename = "show_distribution", skip_serializing_if = "Option::is_none")]
    pub show_distribution: Option<bool>,
    /// Whether to show the error metrics or not.
    #[serde(rename = "show_errors", skip_serializing_if = "Option::is_none")]
    pub show_errors: Option<bool>,
    /// Whether to show the hits metrics or not.
    #[serde(rename = "show_hits", skip_serializing_if = "Option::is_none")]
    pub show_hits: Option<bool>,
    /// Whether to show the latency metrics or not.
    #[serde(rename = "show_latency", skip_serializing_if = "Option::is_none")]
    pub show_latency: Option<bool>,
    /// Whether to show the resource list or not.
    #[serde(rename = "show_resource_list", skip_serializing_if = "Option::is_none")]
    pub show_resource_list: Option<bool>,
    #[serde(rename = "size_format", skip_serializing_if = "Option::is_none")]
    pub size_format: Option<crate::models::WidgetSizeFormat>,
    /// APM span name.
    #[serde(rename = "span_name")]
    pub span_name: String,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<Box<crate::models::WidgetTime>>,
    /// Title of the widget.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "title_align", skip_serializing_if = "Option::is_none")]
    pub title_align: Option<crate::models::WidgetTextAlign>,
    /// Size of the title.
    #[serde(rename = "title_size", skip_serializing_if = "Option::is_none")]
    pub title_size: Option<String>,
    #[serde(rename = "type")]
    pub _type: crate::models::ServiceSummaryWidgetDefinitionType,
}

impl ServiceSummaryWidgetDefinition {
    /// The service summary displays the graphs of a chosen service in your screenboard. Only available on FREE layout dashboards.
    pub fn new(env: String, service: String, span_name: String, _type: crate::models::ServiceSummaryWidgetDefinitionType) -> ServiceSummaryWidgetDefinition {
        ServiceSummaryWidgetDefinition {
            display_format: None,
            env,
            service,
            show_breakdown: None,
            show_distribution: None,
            show_errors: None,
            show_hits: None,
            show_latency: None,
            show_resource_list: None,
            size_format: None,
            span_name,
            time: None,
            title: None,
            title_align: None,
            title_size: None,
            _type,
        }
    }
}


