/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SlackIntegrationChannel : The Slack channel configuration.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SlackIntegrationChannel {
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<Box<crate::models::SlackIntegrationChannelDisplay>>,
    /// Your channel name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl SlackIntegrationChannel {
    /// The Slack channel configuration.
    pub fn new() -> SlackIntegrationChannel {
        SlackIntegrationChannel {
            display: None,
            name: None,
        }
    }
}


