/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SloListResponseMetadata : The metadata object containing additional information about the list of SLOs.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SloListResponseMetadata {
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<Box<crate::models::SloListResponseMetadataPage>>,
}

impl SloListResponseMetadata {
    /// The metadata object containing additional information about the list of SLOs.
    pub fn new() -> SloListResponseMetadata {
        SloListResponseMetadata {
            page: None,
        }
    }
}


