/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SloType : The type of the service level objective.

/// The type of the service level objective.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SloType {
    #[serde(rename = "metric")]
    METRIC,
    #[serde(rename = "monitor")]
    MONITOR,

}

impl ToString for SloType {
    fn to_string(&self) -> String {
        match self {
            Self::METRIC => String::from("metric"),
            Self::MONITOR => String::from("monitor"),
        }
    }
}




