/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SloErrorTimeframe : The timeframe of the threshold associated with this error or \"all\" if all thresholds are affected.

/// The timeframe of the threshold associated with this error or \"all\" if all thresholds are affected.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SloErrorTimeframe {
    #[serde(rename = "7d")]
    SEVEN_DAYS,
    #[serde(rename = "30d")]
    THIRTY_DAYS,
    #[serde(rename = "90d")]
    NINETY_DAYS,
    #[serde(rename = "all")]
    ALL,

}

impl ToString for SloErrorTimeframe {
    fn to_string(&self) -> String {
        match self {
            Self::SEVEN_DAYS => String::from("7d"),
            Self::THIRTY_DAYS => String::from("30d"),
            Self::NINETY_DAYS => String::from("90d"),
            Self::ALL => String::from("all"),
        }
    }
}




