/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SloHistoryResponseError : A service level objective response containing the requested history.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SloHistoryResponseError {
    /// Human readable error.
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl SloHistoryResponseError {
    /// A service level objective response containing the requested history.
    pub fn new() -> SloHistoryResponseError {
        SloHistoryResponseError {
            error: None,
        }
    }
}


