/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SloCorrectionUpdateRequestAttributes : The attribute object associated with the SLO correction to be updated



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SloCorrectionUpdateRequestAttributes {
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<crate::models::SloCorrectionCategory>,
    /// Description of the correction being made.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Ending time of the correction in epoch seconds
    #[serde(rename = "end", skip_serializing_if = "Option::is_none")]
    pub end: Option<i64>,
    /// Starting time of the correction in epoch seconds
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i64>,
    /// The timezone to display in the UI for the correction times (defaults to \"UTC\")
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
}

impl SloCorrectionUpdateRequestAttributes {
    /// The attribute object associated with the SLO correction to be updated
    pub fn new() -> SloCorrectionUpdateRequestAttributes {
        SloCorrectionUpdateRequestAttributes {
            category: None,
            description: None,
            end: None,
            start: None,
            timezone: None,
        }
    }
}


