/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SloCorrectionListResponse : A list of  SLO correction objects



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SloCorrectionListResponse {
    /// The list of of SLO corrections objects
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<crate::models::SloCorrection>>,
}

impl SloCorrectionListResponse {
    /// A list of  SLO correction objects
    pub fn new() -> SloCorrectionListResponse {
        SloCorrectionListResponse {
            data: None,
        }
    }
}


