/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SloTimeframe : The SLO time window options.

/// The SLO time window options.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SloTimeframe {
    #[serde(rename = "7d")]
    SEVEN_DAYS,
    #[serde(rename = "30d")]
    THIRTY_DAYS,
    #[serde(rename = "90d")]
    NINETY_DAYS,

}

impl ToString for SloTimeframe {
    fn to_string(&self) -> String {
        match self {
            Self::SEVEN_DAYS => String::from("7d"),
            Self::THIRTY_DAYS => String::from("30d"),
            Self::NINETY_DAYS => String::from("90d"),
        }
    }
}




