/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SloCorrectionCreateRequest : An object that defines a correction to be applied to an SLO



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SloCorrectionCreateRequest {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::SloCorrectionCreateData>>,
}

impl SloCorrectionCreateRequest {
    /// An object that defines a correction to be applied to an SLO
    pub fn new() -> SloCorrectionCreateRequest {
        SloCorrectionCreateRequest {
            data: None,
        }
    }
}


