/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SloWidgetDefinitionType : Type of the SLO widget.

/// Type of the SLO widget.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SloWidgetDefinitionType {
    #[serde(rename = "slo")]
    SLO,

}

impl ToString for SloWidgetDefinitionType {
    fn to_string(&self) -> String {
        match self {
            Self::SLO => String::from("slo"),
        }
    }
}




