/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SloHistoryMetrics : A `metric` based SLO history response.  This is not included in responses for `monitor` based SLOs.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SloHistoryMetrics {
    #[serde(rename = "denominator")]
    pub denominator: Box<crate::models::SloHistoryMetricsSeries>,
    /// The aggregated query interval for the series data. It's implicit based on the query time window.
    #[serde(rename = "interval")]
    pub interval: i64,
    /// Optional message if there are specific query issues/warnings.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "numerator")]
    pub numerator: Box<crate::models::SloHistoryMetricsSeries>,
    /// The combined numerator and denominator query CSV.
    #[serde(rename = "query")]
    pub query: String,
    /// The series result type. This mimics `batch_query` response type.
    #[serde(rename = "res_type")]
    pub res_type: String,
    /// The series response version type. This mimics `batch_query` response type.
    #[serde(rename = "resp_version")]
    pub resp_version: i64,
    /// An array of query timestamps in EPOCH milliseconds
    #[serde(rename = "times")]
    pub times: Vec<f64>,
}

impl SloHistoryMetrics {
    /// A `metric` based SLO history response.  This is not included in responses for `monitor` based SLOs.
    pub fn new(denominator: crate::models::SloHistoryMetricsSeries, interval: i64, numerator: crate::models::SloHistoryMetricsSeries, query: String, res_type: String, resp_version: i64, times: Vec<f64>) -> SloHistoryMetrics {
        SloHistoryMetrics {
            denominator: Box::new(denominator),
            interval,
            message: None,
            numerator: Box::new(numerator),
            query,
            res_type,
            resp_version,
            times,
        }
    }
}


