/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SloBulkDeleteResponse : The bulk partial delete service level objective object endpoint response.  This endpoint operates on multiple service level objective objects, so it may be partially successful. In such cases, the \"data\" and \"error\" fields in this response indicate which deletions succeeded and failed.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SloBulkDeleteResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::SloBulkDeleteResponseData>>,
    /// Array of errors object returned.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<crate::models::SloBulkDeleteError>>,
}

impl SloBulkDeleteResponse {
    /// The bulk partial delete service level objective object endpoint response.  This endpoint operates on multiple service level objective objects, so it may be partially successful. In such cases, the \"data\" and \"error\" fields in this response indicate which deletions succeeded and failed.
    pub fn new() -> SloBulkDeleteResponse {
        SloBulkDeleteResponse {
            data: None,
            errors: None,
        }
    }
}


