/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SyntheticsBrowserTest : Object containing details about a Synthetic browser test.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyntheticsBrowserTest {
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<Box<crate::models::SyntheticsBrowserTestConfig>>,
    /// Array of locations used to run the test.
    #[serde(rename = "locations", skip_serializing_if = "Option::is_none")]
    pub locations: Option<Vec<String>>,
    /// Notification message associated with the test. Message can either be text or an empty string.
    #[serde(rename = "message")]
    pub message: String,
    /// The associated monitor ID.
    #[serde(rename = "monitor_id", skip_serializing_if = "Option::is_none")]
    pub monitor_id: Option<i64>,
    /// Name of the test.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Box<crate::models::SyntheticsTestOptions>>,
    /// The public ID of the test.
    #[serde(rename = "public_id", skip_serializing_if = "Option::is_none")]
    pub public_id: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::SyntheticsTestPauseStatus>,
    /// The steps of the test.
    #[serde(rename = "steps", skip_serializing_if = "Option::is_none")]
    pub steps: Option<Vec<crate::models::SyntheticsStep>>,
    /// Array of tags attached to the test.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<crate::models::SyntheticsBrowserTestType>,
}

impl SyntheticsBrowserTest {
    /// Object containing details about a Synthetic browser test.
    pub fn new(message: String) -> SyntheticsBrowserTest {
        SyntheticsBrowserTest {
            config: None,
            locations: None,
            message,
            monitor_id: None,
            name: None,
            options: None,
            public_id: None,
            status: None,
            steps: None,
            tags: None,
            _type: None,
        }
    }
}


