/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SyntheticsTriggerCiTestsResponse : Object containing information about the tests triggered.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyntheticsTriggerCiTestsResponse {
    /// List of Synthetics locations.
    #[serde(rename = "locations", skip_serializing_if = "Option::is_none")]
    pub locations: Option<Vec<crate::models::SyntheticsTriggerCiTestLocation>>,
    /// Information about the tests runs.
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<crate::models::SyntheticsTriggerCiTestRunResult>>,
    /// The public IDs of the Synthetics test triggered.
    #[serde(rename = "triggered_check_ids", skip_serializing_if = "Option::is_none")]
    pub triggered_check_ids: Option<Vec<String>>,
}

impl SyntheticsTriggerCiTestsResponse {
    /// Object containing information about the tests triggered.
    pub fn new() -> SyntheticsTriggerCiTestsResponse {
        SyntheticsTriggerCiTestsResponse {
            locations: None,
            results: None,
            triggered_check_ids: None,
        }
    }
}


