/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SyntheticsCiTestMetadataGit : Git information.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyntheticsCiTestMetadataGit {
    /// Branch name.
    #[serde(rename = "branch", skip_serializing_if = "Option::is_none")]
    pub branch: Option<String>,
    /// Commit SHA.
    #[serde(rename = "commit_sha", skip_serializing_if = "Option::is_none")]
    pub commit_sha: Option<String>,
}

impl SyntheticsCiTestMetadataGit {
    /// Git information.
    pub fn new() -> SyntheticsCiTestMetadataGit {
        SyntheticsCiTestMetadataGit {
            branch: None,
            commit_sha: None,
        }
    }
}


