/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SyntheticsErrorCode : Error code that can be returned by a Synthetic test.

/// Error code that can be returned by a Synthetic test.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SyntheticsErrorCode {
    #[serde(rename = "NO_ERROR")]
    NO_ERROR,
    #[serde(rename = "UNKNOWN")]
    UNKNOWN,
    #[serde(rename = "DNS")]
    DNS,
    #[serde(rename = "SSL")]
    SSL,
    #[serde(rename = "TIMEOUT")]
    TIMEOUT,
    #[serde(rename = "DENIED")]
    DENIED,
    #[serde(rename = "INCORRECT_ASSERTION")]
    INCORRECT_ASSERTION,

}

impl ToString for SyntheticsErrorCode {
    fn to_string(&self) -> String {
        match self {
            Self::NO_ERROR => String::from("NO_ERROR"),
            Self::UNKNOWN => String::from("UNKNOWN"),
            Self::DNS => String::from("DNS"),
            Self::SSL => String::from("SSL"),
            Self::TIMEOUT => String::from("TIMEOUT"),
            Self::DENIED => String::from("DENIED"),
            Self::INCORRECT_ASSERTION => String::from("INCORRECT_ASSERTION"),
        }
    }
}




