/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SyntheticsTestRequestCertificateItem : Define a request certificate.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyntheticsTestRequestCertificateItem {
    /// Content of the certificate or key.
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// File name for the certificate or key.
    #[serde(rename = "filename", skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    /// Date of update of the certificate or key, ISO format.
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl SyntheticsTestRequestCertificateItem {
    /// Define a request certificate.
    pub fn new() -> SyntheticsTestRequestCertificateItem {
        SyntheticsTestRequestCertificateItem {
            content: None,
            filename: None,
            updated_at: None,
        }
    }
}


