/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SyntheticsGlobalVariable : Synthetics global variable.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyntheticsGlobalVariable {
    /// Description of the global variable.
    #[serde(rename = "description")]
    pub description: String,
    /// Unique identifier of the global variable.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Name of the global variable.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "parse_test_options", skip_serializing_if = "Option::is_none")]
    pub parse_test_options: Option<Box<crate::models::SyntheticsGlobalVariableParseTestOptions>>,
    /// A Synthetic test ID to use as a test to generate the variable value.
    #[serde(rename = "parse_test_public_id", skip_serializing_if = "Option::is_none")]
    pub parse_test_public_id: Option<String>,
    /// Tags of the global variable.
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
    #[serde(rename = "value")]
    pub value: Box<crate::models::SyntheticsGlobalVariableValue>,
}

impl SyntheticsGlobalVariable {
    /// Synthetics global variable.
    pub fn new(description: String, name: String, tags: Vec<String>, value: crate::models::SyntheticsGlobalVariableValue) -> SyntheticsGlobalVariable {
        SyntheticsGlobalVariable {
            description,
            id: None,
            name,
            parse_test_options: None,
            parse_test_public_id: None,
            tags,
            value: Box::new(value),
        }
    }
}


