/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SyntheticsTriggerCiTestLocation : Synthetics location.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyntheticsTriggerCiTestLocation {
    /// Unique identifier of the location.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// Name of the location.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl SyntheticsTriggerCiTestLocation {
    /// Synthetics location.
    pub fn new() -> SyntheticsTriggerCiTestLocation {
        SyntheticsTriggerCiTestLocation {
            id: None,
            name: None,
        }
    }
}


