/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SyntheticsDeletedTest : Object containing a deleted Synthetic test ID with the associated deletion timestamp.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyntheticsDeletedTest {
    /// Deletion timestamp of the Synthetic test ID.
    #[serde(rename = "deleted_at", skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<String>,
    /// The Synthetic test ID deleted.
    #[serde(rename = "public_id", skip_serializing_if = "Option::is_none")]
    pub public_id: Option<String>,
}

impl SyntheticsDeletedTest {
    /// Object containing a deleted Synthetic test ID with the associated deletion timestamp.
    pub fn new() -> SyntheticsDeletedTest {
        SyntheticsDeletedTest {
            deleted_at: None,
            public_id: None,
        }
    }
}


