/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SyntheticsBrowserVariable : Object defining a variable that can be used in your browser test. Learn more in the [Browser test Actions documentation](https://docs.datadoghq.com/synthetics/browser_tests/actions#variable).



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyntheticsBrowserVariable {
    /// Example for the variable.
    #[serde(rename = "example", skip_serializing_if = "Option::is_none")]
    pub example: Option<String>,
    /// ID for the variable.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Name of the variable.
    #[serde(rename = "name")]
    pub name: String,
    /// Pattern of the variable.
    #[serde(rename = "pattern", skip_serializing_if = "Option::is_none")]
    pub pattern: Option<String>,
    #[serde(rename = "type")]
    pub _type: crate::models::SyntheticsBrowserVariableType,
}

impl SyntheticsBrowserVariable {
    /// Object defining a variable that can be used in your browser test. Learn more in the [Browser test Actions documentation](https://docs.datadoghq.com/synthetics/browser_tests/actions#variable).
    pub fn new(name: String, _type: crate::models::SyntheticsBrowserVariableType) -> SyntheticsBrowserVariable {
        SyntheticsBrowserVariable {
            example: None,
            id: None,
            name,
            pattern: None,
            _type,
        }
    }
}


