/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SyntheticsTiming : Object containing all metrics and their values collected for a Synthetic API test. Learn more about those metrics in [Synthetics documentation](https://docs.datadoghq.com/synthetics/#metrics).



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyntheticsTiming {
    /// The duration in millisecond of the DNS lookup.
    #[serde(rename = "dns", skip_serializing_if = "Option::is_none")]
    pub dns: Option<f64>,
    /// The time in millisecond to download the response.
    #[serde(rename = "download", skip_serializing_if = "Option::is_none")]
    pub download: Option<f64>,
    /// The time in millisecond to first byte.
    #[serde(rename = "firstByte", skip_serializing_if = "Option::is_none")]
    pub first_byte: Option<f64>,
    /// The duration in millisecond of the TLS handshake.
    #[serde(rename = "handshake", skip_serializing_if = "Option::is_none")]
    pub handshake: Option<f64>,
    /// The time in millisecond spent during redirections.
    #[serde(rename = "redirect", skip_serializing_if = "Option::is_none")]
    pub redirect: Option<f64>,
    /// The duration in millisecond of the TLS handshake.
    #[serde(rename = "ssl", skip_serializing_if = "Option::is_none")]
    pub ssl: Option<f64>,
    /// Time in millisecond to establish the TCP connection.
    #[serde(rename = "tcp", skip_serializing_if = "Option::is_none")]
    pub tcp: Option<f64>,
    /// The overall time in millisecond the request took to be processed.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<f64>,
    /// Time spent in millisecond waiting for a response.
    #[serde(rename = "wait", skip_serializing_if = "Option::is_none")]
    pub wait: Option<f64>,
}

impl SyntheticsTiming {
    /// Object containing all metrics and their values collected for a Synthetic API test. Learn more about those metrics in [Synthetics documentation](https://docs.datadoghq.com/synthetics/#metrics).
    pub fn new() -> SyntheticsTiming {
        SyntheticsTiming {
            dns: None,
            download: None,
            first_byte: None,
            handshake: None,
            redirect: None,
            ssl: None,
            tcp: None,
            total: None,
            wait: None,
        }
    }
}


