/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SyntheticsGlobalVariableValue : Value of the global variable.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyntheticsGlobalVariableValue {
    /// Determines if the variable is secure.
    #[serde(rename = "secure", skip_serializing_if = "Option::is_none")]
    pub secure: Option<bool>,
    /// Value of the global variable. When reading a global variable, the value will not be present if the variable is secure.
    #[serde(rename = "value")]
    pub value: String,
}

impl SyntheticsGlobalVariableValue {
    /// Value of the global variable.
    pub fn new(value: String) -> SyntheticsGlobalVariableValue {
        SyntheticsGlobalVariableValue {
            secure: None,
            value,
        }
    }
}


