/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SyntheticsSslCertificateIssuer : Object describing the issuer of a SSL certificate.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyntheticsSslCertificateIssuer {
    /// Country Name that issued the certificate.
    #[serde(rename = "C", skip_serializing_if = "Option::is_none")]
    pub C: Option<String>,
    /// Common Name that issued certificate.
    #[serde(rename = "CN", skip_serializing_if = "Option::is_none")]
    pub CN: Option<String>,
    /// Locality that issued the certificate.
    #[serde(rename = "L", skip_serializing_if = "Option::is_none")]
    pub L: Option<String>,
    /// Organization that issued the certificate.
    #[serde(rename = "O", skip_serializing_if = "Option::is_none")]
    pub O: Option<String>,
    /// Organizational Unit that issued the certificate.
    #[serde(rename = "OU", skip_serializing_if = "Option::is_none")]
    pub OU: Option<String>,
    /// State Or Province Name that issued the certificate.
    #[serde(rename = "ST", skip_serializing_if = "Option::is_none")]
    pub ST: Option<String>,
}

impl SyntheticsSslCertificateIssuer {
    /// Object describing the issuer of a SSL certificate.
    pub fn new() -> SyntheticsSslCertificateIssuer {
        SyntheticsSslCertificateIssuer {
            C: None,
            CN: None,
            L: None,
            O: None,
            OU: None,
            ST: None,
        }
    }
}


