/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SyntheticsPrivateLocationSecretsAuthentication : Authentication part of the secrets.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyntheticsPrivateLocationSecretsAuthentication {
    /// Access key for the private location.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Secret access key for the private location.
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
}

impl SyntheticsPrivateLocationSecretsAuthentication {
    /// Authentication part of the secrets.
    pub fn new() -> SyntheticsPrivateLocationSecretsAuthentication {
        SyntheticsPrivateLocationSecretsAuthentication {
            id: None,
            key: None,
        }
    }
}


