/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SyntheticsPrivateLocationCreationResponse : Object that contains the new private location, the public key for result encryption, and the configuration skeleton.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyntheticsPrivateLocationCreationResponse {
    /// Configuration skeleton for the private location. See installation instructions of the private location on how to use this configuration.
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<serde_json::Value>,
    #[serde(rename = "private_location", skip_serializing_if = "Option::is_none")]
    pub private_location: Option<Box<crate::models::SyntheticsPrivateLocation>>,
    #[serde(rename = "result_encryption", skip_serializing_if = "Option::is_none")]
    pub result_encryption: Option<Box<crate::models::SyntheticsPrivateLocationCreationResponseResultEncryption>>,
}

impl SyntheticsPrivateLocationCreationResponse {
    /// Object that contains the new private location, the public key for result encryption, and the configuration skeleton.
    pub fn new() -> SyntheticsPrivateLocationCreationResponse {
        SyntheticsPrivateLocationCreationResponse {
            config: None,
            private_location: None,
            result_encryption: None,
        }
    }
}


