/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SyntheticsAssertionTarget : An assertion which uses a simple target.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyntheticsAssertionTarget {
    #[serde(rename = "operator")]
    pub operator: crate::models::SyntheticsAssertionOperator,
    /// The associated assertion property.
    #[serde(rename = "property", skip_serializing_if = "Option::is_none")]
    pub property: Option<String>,
    /// Value used by the operator.
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<serde_json::Value>,
    #[serde(rename = "type")]
    pub _type: crate::models::SyntheticsAssertionType,
}

impl SyntheticsAssertionTarget {
    /// An assertion which uses a simple target.
    pub fn new(operator: crate::models::SyntheticsAssertionOperator, _type: crate::models::SyntheticsAssertionType) -> SyntheticsAssertionTarget {
        SyntheticsAssertionTarget {
            operator,
            property: None,
            target: None,
            _type,
        }
    }
}


