/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SyntheticsWarningType : User locator used.

/// User locator used.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SyntheticsWarningType {
    #[serde(rename = "user_locator")]
    USER_LOCATOR,

}

impl ToString for SyntheticsWarningType {
    fn to_string(&self) -> String {
        match self {
            Self::USER_LOCATOR => String::from("user_locator"),
        }
    }
}




