/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// SyntheticsTestDetailsType : Type of the Synthetic test, either `api` or `browser`.

/// Type of the Synthetic test, either `api` or `browser`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SyntheticsTestDetailsType {
    #[serde(rename = "api")]
    API,
    #[serde(rename = "browser")]
    BROWSER,

}

impl ToString for SyntheticsTestDetailsType {
    fn to_string(&self) -> String {
        match self {
            Self::API => String::from("api"),
            Self::BROWSER => String::from("browser"),
        }
    }
}




