/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// TimeseriesWidgetExpressionAlias : Define an expression alias.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeseriesWidgetExpressionAlias {
    /// Expression alias.
    #[serde(rename = "alias_name", skip_serializing_if = "Option::is_none")]
    pub alias_name: Option<String>,
    /// Expression name.
    #[serde(rename = "expression")]
    pub expression: String,
}

impl TimeseriesWidgetExpressionAlias {
    /// Define an expression alias.
    pub fn new(expression: String) -> TimeseriesWidgetExpressionAlias {
        TimeseriesWidgetExpressionAlias {
            alias_name: None,
            expression,
        }
    }
}


