/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageTraceHour : The hours of trace usage.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageTraceHour {
    /// The hour for the usage.
    #[serde(rename = "hour", skip_serializing_if = "Option::is_none")]
    pub hour: Option<String>,
    /// Contains the number of Indexed Spans indexed.
    #[serde(rename = "indexed_events_count", skip_serializing_if = "Option::is_none")]
    pub indexed_events_count: Option<i64>,
}

impl UsageTraceHour {
    /// The hours of trace usage.
    pub fn new() -> UsageTraceHour {
        UsageTraceHour {
            hour: None,
            indexed_events_count: None,
        }
    }
}


