/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageCustomReportsPage : The object containing page total count.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageCustomReportsPage {
    /// Total page count.
    #[serde(rename = "total_count", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<i64>,
}

impl UsageCustomReportsPage {
    /// The object containing page total count.
    pub fn new() -> UsageCustomReportsPage {
        UsageCustomReportsPage {
            total_count: None,
        }
    }
}


