/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageHostsResponse : Host usage response.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageHostsResponse {
    /// An array of objects related to host usage.
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<Vec<crate::models::UsageHostHour>>,
}

impl UsageHostsResponse {
    /// Host usage response.
    pub fn new() -> UsageHostsResponse {
        UsageHostsResponse {
            usage: None,
        }
    }
}


