/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageNetworkHostsHour : Number of active NPM hosts for each hour for a given organization.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageNetworkHostsHour {
    /// Contains the number of active NPM hosts.
    #[serde(rename = "host_count", skip_serializing_if = "Option::is_none")]
    pub host_count: Option<i64>,
    /// The hour for the usage.
    #[serde(rename = "hour", skip_serializing_if = "Option::is_none")]
    pub hour: Option<String>,
}

impl UsageNetworkHostsHour {
    /// Number of active NPM hosts for each hour for a given organization.
    pub fn new() -> UsageNetworkHostsHour {
        UsageNetworkHostsHour {
            host_count: None,
            hour: None,
        }
    }
}


