/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageSyntheticsHour : The number of synthetics tests run for each hour for a given organization.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageSyntheticsHour {
    /// Contains the number of Synthetics API tests run.
    #[serde(rename = "check_calls_count", skip_serializing_if = "Option::is_none")]
    pub check_calls_count: Option<i64>,
    /// The hour for the usage.
    #[serde(rename = "hour", skip_serializing_if = "Option::is_none")]
    pub hour: Option<String>,
}

impl UsageSyntheticsHour {
    /// The number of synthetics tests run for each hour for a given organization.
    pub fn new() -> UsageSyntheticsHour {
        UsageSyntheticsHour {
            check_calls_count: None,
            hour: None,
        }
    }
}


