/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageLogsResponse : Response containing the number of logs for each hour.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageLogsResponse {
    /// An array of objects regarding hourly usage of logs.
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<Vec<crate::models::UsageLogsHour>>,
}

impl UsageLogsResponse {
    /// Response containing the number of logs for each hour.
    pub fn new() -> UsageLogsResponse {
        UsageLogsResponse {
            usage: None,
        }
    }
}


