/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageTopAvgMetricsMetadata : The object containing document metadata.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageTopAvgMetricsMetadata {
    /// The day value from the user request that contains the returned usage data. (If day was used the request)
    #[serde(rename = "day", skip_serializing_if = "Option::is_none")]
    pub day: Option<serde_json::Value>,
    /// The month value from the user request that contains the returned usage data. (If month was used the request)
    #[serde(rename = "month", skip_serializing_if = "Option::is_none")]
    pub month: Option<serde_json::Value>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::UsageAttributionPagination>>,
}

impl UsageTopAvgMetricsMetadata {
    /// The object containing document metadata.
    pub fn new() -> UsageTopAvgMetricsMetadata {
        UsageTopAvgMetricsMetadata {
            day: None,
            month: None,
            pagination: None,
        }
    }
}


