/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageSpecifiedCustomReportsPage : The object containing page total count for specified ID.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageSpecifiedCustomReportsPage {
    /// Total page count.
    #[serde(rename = "total_count", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<i64>,
}

impl UsageSpecifiedCustomReportsPage {
    /// The object containing page total count for specified ID.
    pub fn new() -> UsageSpecifiedCustomReportsPage {
        UsageSpecifiedCustomReportsPage {
            total_count: None,
        }
    }
}


