/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageRumSessionsResponse : Response containing the number of RUM Sessions for each hour for a given organization.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageRumSessionsResponse {
    /// Get hourly usage for RUM Sessions.
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<Vec<crate::models::UsageRumSessionsHour>>,
}

impl UsageRumSessionsResponse {
    /// Response containing the number of RUM Sessions for each hour for a given organization.
    pub fn new() -> UsageRumSessionsResponse {
        UsageRumSessionsResponse {
            usage: None,
        }
    }
}


