/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageNetworkFlowsHour : Number of netflow events indexed for each hour for a given organization.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageNetworkFlowsHour {
    /// The hour for the usage.
    #[serde(rename = "hour", skip_serializing_if = "Option::is_none")]
    pub hour: Option<String>,
    /// Contains the number of netflow events indexed.
    #[serde(rename = "indexed_event_count", skip_serializing_if = "Option::is_none")]
    pub indexed_event_count: Option<i64>,
}

impl UsageNetworkFlowsHour {
    /// Number of netflow events indexed for each hour for a given organization.
    pub fn new() -> UsageNetworkFlowsHour {
        UsageNetworkFlowsHour {
            hour: None,
            indexed_event_count: None,
        }
    }
}


