/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageBillableSummaryHour : Response with monthly summary of data billed by Datadog.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageBillableSummaryHour {
    /// The billing plan.
    #[serde(rename = "billing_plan", skip_serializing_if = "Option::is_none")]
    pub billing_plan: Option<String>,
    /// Shows the last date of usage.
    #[serde(rename = "end_date", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
    /// The number of organizations.
    #[serde(rename = "num_orgs", skip_serializing_if = "Option::is_none")]
    pub num_orgs: Option<i64>,
    /// The organization name.
    #[serde(rename = "org_name", skip_serializing_if = "Option::is_none")]
    pub org_name: Option<String>,
    /// The organization public ID.
    #[serde(rename = "public_id", skip_serializing_if = "Option::is_none")]
    pub public_id: Option<String>,
    /// Shows usage aggregation for a billing period.
    #[serde(rename = "ratio_in_month", skip_serializing_if = "Option::is_none")]
    pub ratio_in_month: Option<i64>,
    /// Shows the first date of usage.
    #[serde(rename = "start_date", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<Box<crate::models::UsageBillableSummaryKeys>>,
}

impl UsageBillableSummaryHour {
    /// Response with monthly summary of data billed by Datadog.
    pub fn new() -> UsageBillableSummaryHour {
        UsageBillableSummaryHour {
            billing_plan: None,
            end_date: None,
            num_orgs: None,
            org_name: None,
            public_id: None,
            ratio_in_month: None,
            start_date: None,
            usage: None,
        }
    }
}


