/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageCustomReportsData : The response containing the date and type for custom reports.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageCustomReportsData {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::UsageCustomReportsAttributes>>,
    /// The date for specified custom reports.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<crate::models::UsageReportsType>,
}

impl UsageCustomReportsData {
    /// The response containing the date and type for custom reports.
    pub fn new() -> UsageCustomReportsData {
        UsageCustomReportsData {
            attributes: None,
            id: None,
            _type: None,
        }
    }
}


