/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageMetricCategory : Contains the metric category.

/// Contains the metric category.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UsageMetricCategory {
    #[serde(rename = "standard")]
    STANDARD,
    #[serde(rename = "custom")]
    CUSTOM,

}

impl ToString for UsageMetricCategory {
    fn to_string(&self) -> String {
        match self {
            Self::STANDARD => String::from("standard"),
            Self::CUSTOM => String::from("custom"),
        }
    }
}




