/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageAttributionResponse : Response containing the Usage Summary by tag(s).



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageAttributionResponse {
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<crate::models::UsageAttributionMetadata>>,
    /// Get Usage Summary by tag(s).
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<Vec<crate::models::UsageAttributionBody>>,
}

impl UsageAttributionResponse {
    /// Response containing the Usage Summary by tag(s).
    pub fn new() -> UsageAttributionResponse {
        UsageAttributionResponse {
            metadata: None,
            usage: None,
        }
    }
}


