/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageComplianceResponse : The response containing the Compliance Monitoring usage for each hour for a given organization.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageComplianceResponse {
    /// Get hourly usage for Compliance Monitoring.
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<Vec<crate::models::UsageComplianceHour>>,
}

impl UsageComplianceResponse {
    /// The response containing the Compliance Monitoring usage for each hour for a given organization.
    pub fn new() -> UsageComplianceResponse {
        UsageComplianceResponse {
            usage: None,
        }
    }
}


