/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageIngestedSpansResponse : Response containing the ingested spans usage for each hour for a given organization.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageIngestedSpansResponse {
    /// Get hourly usage for ingested spans.
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<Vec<crate::models::UsageIngestedSpansHour>>,
}

impl UsageIngestedSpansResponse {
    /// Response containing the ingested spans usage for each hour for a given organization.
    pub fn new() -> UsageIngestedSpansResponse {
        UsageIngestedSpansResponse {
            usage: None,
        }
    }
}


