/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageSort : The field to sort by.

/// The field to sort by.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UsageSort {
    #[serde(rename = "computed_on")]
    COMPUTED_ON,
    #[serde(rename = "size")]
    SIZE,
    #[serde(rename = "start_date")]
    START_DATE,
    #[serde(rename = "end_date")]
    END_DATE,

}

impl ToString for UsageSort {
    fn to_string(&self) -> String {
        match self {
            Self::COMPUTED_ON => String::from("computed_on"),
            Self::SIZE => String::from("size"),
            Self::START_DATE => String::from("start_date"),
            Self::END_DATE => String::from("end_date"),
        }
    }
}




