/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageSyntheticsApiResponse : Response containing the number of Synthetics API tests run for each hour for a given organization.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageSyntheticsApiResponse {
    /// Get hourly usage for Synthetics API tests.
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<Vec<crate::models::UsageSyntheticsApiHour>>,
}

impl UsageSyntheticsApiResponse {
    /// Response containing the number of Synthetics API tests run for each hour for a given organization.
    pub fn new() -> UsageSyntheticsApiResponse {
        UsageSyntheticsApiResponse {
            usage: None,
        }
    }
}


