/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageAttributionMetadata : The object containing document metadata.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageAttributionMetadata {
    /// An array of available aggregates.
    #[serde(rename = "aggregates", skip_serializing_if = "Option::is_none")]
    pub aggregates: Option<Vec<crate::models::UsageAttributionAggregatesBody>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::UsageAttributionPagination>>,
}

impl UsageAttributionMetadata {
    /// The object containing document metadata.
    pub fn new() -> UsageAttributionMetadata {
        UsageAttributionMetadata {
            aggregates: None,
            pagination: None,
        }
    }
}


