/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageIndexedSpansResponse : A response containing indexed spans usage.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageIndexedSpansResponse {
    /// Array with the number of hourly traces indexed for a given organization.
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<Vec<crate::models::UsageIndexedSpansHour>>,
}

impl UsageIndexedSpansResponse {
    /// A response containing indexed spans usage.
    pub fn new() -> UsageIndexedSpansResponse {
        UsageIndexedSpansResponse {
            usage: None,
        }
    }
}


