/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageSnmpResponse : Response containing the number of SNMP devices for each hour for a given organization.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageSnmpResponse {
    /// Get hourly usage for SNMP devices.
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<Vec<crate::models::UsageSnmpHour>>,
}

impl UsageSnmpResponse {
    /// Response containing the number of SNMP devices for each hour for a given organization.
    pub fn new() -> UsageSnmpResponse {
        UsageSnmpResponse {
            usage: None,
        }
    }
}


