/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageBillableSummaryKeys : Response with aggregated usage types.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageBillableSummaryKeys {
    #[serde(rename = "apm_host_sum", skip_serializing_if = "Option::is_none")]
    pub apm_host_sum: Option<Box<crate::models::UsageBillableSummaryBody>>,
    #[serde(rename = "apm_host_top99p", skip_serializing_if = "Option::is_none")]
    pub apm_host_top99p: Option<Box<crate::models::UsageBillableSummaryBody>>,
    #[serde(rename = "apm_trace_search_sum", skip_serializing_if = "Option::is_none")]
    pub apm_trace_search_sum: Option<Box<crate::models::UsageBillableSummaryBody>>,
    #[serde(rename = "fargate_container_average", skip_serializing_if = "Option::is_none")]
    pub fargate_container_average: Option<Box<crate::models::UsageBillableSummaryBody>>,
    #[serde(rename = "infra_container_sum", skip_serializing_if = "Option::is_none")]
    pub infra_container_sum: Option<Box<crate::models::UsageBillableSummaryBody>>,
    #[serde(rename = "infra_host_sum", skip_serializing_if = "Option::is_none")]
    pub infra_host_sum: Option<Box<crate::models::UsageBillableSummaryBody>>,
    #[serde(rename = "infra_host_top99p", skip_serializing_if = "Option::is_none")]
    pub infra_host_top99p: Option<Box<crate::models::UsageBillableSummaryBody>>,
    #[serde(rename = "iot_top99p", skip_serializing_if = "Option::is_none")]
    pub iot_top99p: Option<Box<crate::models::UsageBillableSummaryBody>>,
    #[serde(rename = "lambda_function_average", skip_serializing_if = "Option::is_none")]
    pub lambda_function_average: Option<Box<crate::models::UsageBillableSummaryBody>>,
    #[serde(rename = "logs_indexed_sum", skip_serializing_if = "Option::is_none")]
    pub logs_indexed_sum: Option<Box<crate::models::UsageBillableSummaryBody>>,
    #[serde(rename = "logs_ingested_sum", skip_serializing_if = "Option::is_none")]
    pub logs_ingested_sum: Option<Box<crate::models::UsageBillableSummaryBody>>,
    #[serde(rename = "npm_flow_sum", skip_serializing_if = "Option::is_none")]
    pub npm_flow_sum: Option<Box<crate::models::UsageBillableSummaryBody>>,
    #[serde(rename = "npm_host_top99p", skip_serializing_if = "Option::is_none")]
    pub npm_host_top99p: Option<Box<crate::models::UsageBillableSummaryBody>>,
    #[serde(rename = "rum_sum", skip_serializing_if = "Option::is_none")]
    pub rum_sum: Option<Box<crate::models::UsageBillableSummaryBody>>,
    #[serde(rename = "serverless_invocation_sum", skip_serializing_if = "Option::is_none")]
    pub serverless_invocation_sum: Option<Box<crate::models::UsageBillableSummaryBody>>,
    #[serde(rename = "siem_sum", skip_serializing_if = "Option::is_none")]
    pub siem_sum: Option<Box<crate::models::UsageBillableSummaryBody>>,
    #[serde(rename = "synthetics_api_tests_sum", skip_serializing_if = "Option::is_none")]
    pub synthetics_api_tests_sum: Option<Box<crate::models::UsageBillableSummaryBody>>,
    #[serde(rename = "synthetics_browser_checks_sum", skip_serializing_if = "Option::is_none")]
    pub synthetics_browser_checks_sum: Option<Box<crate::models::UsageBillableSummaryBody>>,
    #[serde(rename = "timeseries_average", skip_serializing_if = "Option::is_none")]
    pub timeseries_average: Option<Box<crate::models::UsageBillableSummaryBody>>,
}

impl UsageBillableSummaryKeys {
    /// Response with aggregated usage types.
    pub fn new() -> UsageBillableSummaryKeys {
        UsageBillableSummaryKeys {
            apm_host_sum: None,
            apm_host_top99p: None,
            apm_trace_search_sum: None,
            fargate_container_average: None,
            infra_container_sum: None,
            infra_host_sum: None,
            infra_host_top99p: None,
            iot_top99p: None,
            lambda_function_average: None,
            logs_indexed_sum: None,
            logs_ingested_sum: None,
            npm_flow_sum: None,
            npm_host_top99p: None,
            rum_sum: None,
            serverless_invocation_sum: None,
            siem_sum: None,
            synthetics_api_tests_sum: None,
            synthetics_browser_checks_sum: None,
            timeseries_average: None,
        }
    }
}


