/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageProfilingResponse : Response containing the number of profiled hosts for each hour for a given organization.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageProfilingResponse {
    /// Get hourly usage for profiled hosts.
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<Vec<crate::models::UsageProfilingHour>>,
}

impl UsageProfilingResponse {
    /// Response containing the number of profiled hosts for each hour for a given organization.
    pub fn new() -> UsageProfilingResponse {
        UsageProfilingResponse {
            usage: None,
        }
    }
}


