/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageTracingWithoutLimitsHour : Tracing without limits usage for a given organization for a given hour.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageTracingWithoutLimitsHour {
    /// The hour for the usage.
    #[serde(rename = "hour", skip_serializing_if = "Option::is_none")]
    pub hour: Option<String>,
    /// Contains the total number of bytes ingested during a given hour.
    #[serde(rename = "ingested_events_bytes", skip_serializing_if = "Option::is_none")]
    pub ingested_events_bytes: Option<i64>,
}

impl UsageTracingWithoutLimitsHour {
    /// Tracing without limits usage for a given organization for a given hour.
    pub fn new() -> UsageTracingWithoutLimitsHour {
        UsageTracingWithoutLimitsHour {
            hour: None,
            ingested_events_bytes: None,
        }
    }
}


