/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// UsageIoTHour : IoT usage for a given organization for a given hour.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageIoTHour {
    /// The hour for the usage.
    #[serde(rename = "hour", skip_serializing_if = "Option::is_none")]
    pub hour: Option<String>,
    /// The total number of IoT devices during a given hour.
    #[serde(rename = "iot_device_count", skip_serializing_if = "Option::is_none")]
    pub iot_device_count: Option<i64>,
}

impl UsageIoTHour {
    /// IoT usage for a given organization for a given hour.
    pub fn new() -> UsageIoTHour {
        UsageIoTHour {
            hour: None,
            iot_device_count: None,
        }
    }
}


