/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// WidgetNodeType : Which type of node to use in the map.

/// Which type of node to use in the map.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WidgetNodeType {
    #[serde(rename = "host")]
    HOST,
    #[serde(rename = "container")]
    CONTAINER,

}

impl ToString for WidgetNodeType {
    fn to_string(&self) -> String {
        match self {
            Self::HOST => String::from("host"),
            Self::CONTAINER => String::from("container"),
        }
    }
}




