/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// WidgetAxis : Axis controls for the widget.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WidgetAxis {
    /// True includes zero.
    #[serde(rename = "include_zero", skip_serializing_if = "Option::is_none")]
    pub include_zero: Option<bool>,
    /// The label of the axis to display on the graph.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// Specifies the maximum value to show on the y-axis. It takes a number, or auto for default behavior.
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<String>,
    /// Specifies minimum value to show on the y-axis. It takes a number, or auto for default behavior.
    #[serde(rename = "min", skip_serializing_if = "Option::is_none")]
    pub min: Option<String>,
    /// Specifies the scale type. Possible values are `linear`, `log`, `sqrt`, `pow##` (e.g. `pow2`, `pow0.5` etc.).
    #[serde(rename = "scale", skip_serializing_if = "Option::is_none")]
    pub scale: Option<String>,
}

impl WidgetAxis {
    /// Axis controls for the widget.
    pub fn new() -> WidgetAxis {
        WidgetAxis {
            include_zero: None,
            label: None,
            max: None,
            min: None,
            scale: None,
        }
    }
}


