/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// WidgetEventSize : Size to use to display an event.

/// Size to use to display an event.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WidgetEventSize {
    #[serde(rename = "s")]
    SMALL,
    #[serde(rename = "l")]
    LARGE,

}

impl ToString for WidgetEventSize {
    fn to_string(&self) -> String {
        match self {
            Self::SMALL => String::from("s"),
            Self::LARGE => String::from("l"),
        }
    }
}




