/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// WidgetDisplayType : Type of display to use for the request.

/// Type of display to use for the request.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WidgetDisplayType {
    #[serde(rename = "area")]
    AREA,
    #[serde(rename = "bars")]
    BARS,
    #[serde(rename = "line")]
    LINE,

}

impl ToString for WidgetDisplayType {
    fn to_string(&self) -> String {
        match self {
            Self::AREA => String::from("area"),
            Self::BARS => String::from("bars"),
            Self::LINE => String::from("line"),
        }
    }
}




