/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// WidgetMarker : Markers allow you to add visual conditional formatting for your graphs.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WidgetMarker {
    /// Combination of:   - A severity error, warning, ok, or info   - A line type: dashed, solid, or bold In this case of a Distribution widget, this can be set to be `x_axis_percentile`. 
    #[serde(rename = "display_type", skip_serializing_if = "Option::is_none")]
    pub display_type: Option<String>,
    /// Label to display over the marker.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// Timestamp for the widget.
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
    /// Value to apply. Can be a single value y = 15 or a range of values 0 < y < 10.
    #[serde(rename = "value")]
    pub value: String,
}

impl WidgetMarker {
    /// Markers allow you to add visual conditional formatting for your graphs.
    pub fn new(value: String) -> WidgetMarker {
        WidgetMarker {
            display_type: None,
            label: None,
            time: None,
            value,
        }
    }
}


