/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// WidgetFormula : Formula to be used in a widget query.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WidgetFormula {
    /// Expression alias.
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    /// String expression built from queries, formulas, and functions.
    #[serde(rename = "formula")]
    pub formula: String,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<Box<crate::models::WidgetFormulaLimit>>,
}

impl WidgetFormula {
    /// Formula to be used in a widget query.
    pub fn new(formula: String) -> WidgetFormula {
        WidgetFormula {
            alias: None,
            formula,
            limit: None,
        }
    }
}


