/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// WidgetStyle : Widget style definition.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WidgetStyle {
    /// Color palette to apply to the widget.
    #[serde(rename = "palette", skip_serializing_if = "Option::is_none")]
    pub palette: Option<String>,
}

impl WidgetStyle {
    /// Widget style definition.
    pub fn new() -> WidgetStyle {
        WidgetStyle {
            palette: None,
        }
    }
}


