/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// WidgetSort : Widget sorting methods.

/// Widget sorting methods.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WidgetSort {
    #[serde(rename = "asc")]
    ASCENDING,
    #[serde(rename = "desc")]
    DESCENDING,

}

impl ToString for WidgetSort {
    fn to_string(&self) -> String {
        match self {
            Self::ASCENDING => String::from("asc"),
            Self::DESCENDING => String::from("desc"),
        }
    }
}




