/*
 * Datadog API V1 Collection
 *
 * Collection of all Datadog Public endpoints.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@datadoghq.com
 * Generated by: https://openapi-generator.tech
 */

/// WidgetLineType : Type of lines displayed.

/// Type of lines displayed.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WidgetLineType {
    #[serde(rename = "dashed")]
    DASHED,
    #[serde(rename = "dotted")]
    DOTTED,
    #[serde(rename = "solid")]
    SOLID,

}

impl ToString for WidgetLineType {
    fn to_string(&self) -> String {
        match self {
            Self::DASHED => String::from("dashed"),
            Self::DOTTED => String::from("dotted"),
            Self::SOLID => String::from("solid"),
        }
    }
}




